name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Install Docker Compose CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin

    - name: Run tests
      run: pytest tests/

    - name: Build Docker image
      run: docker build -t python-app .

    - name: Run Docker Compose (optional, for integration tests)
      run: docker-compose up -d

    - name: Wait for services to be healthy (optional)
      run: sleep 10 # Adjust as needed

    - name: Run integration tests (optional)
      run: echo "No integration tests configured yet."

    - name: Stop Docker Compose (optional)
      run: docker-compose down
